   
SELECT * FROM DB.HR  ;


-- OVERALL ATTRITION RATE IN THE COMPANY
SELECT
    COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) AS ATTRITIONCOUNT,
    COUNT(*) AS TOTALEMPLOYEES,
    (COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) / COUNT(*)) * 100 AS ATTRITIONRATE
FROM
   HR ;
   
   -- DIFFERENCE IN ATTRITION RATES BETWEEN DIFFERENT AGE BANDS OR DEPARTMENTS
  SELECT
    CF_AGEBAND,
    COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) AS ATTRITIONCOUNT,
    COUNT(*) AS TOTALEMPLOYEES,
    (COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) / COUNT(*)) * 100 AS ATTRITIONRATE
FROM
     HR
GROUP BY
   CF_AGEBAND;

-- PRESENCE OF OVERTIME HAVE ANY CORRELATION WITH ATTRITION

SELECT OVERTIME,
    COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) AS OVERTIMECOUNT ,
    COUNT(*) AS TOTALEMPLOYEES,
    (COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) / COUNT(*)) * 100 AS CORRELATIONRATE
FROM HR 
GROUP BY
    OVERTIME;
    
    -- GENDER DISTRIBUTION AMONG EMPLOYEES
    SELECT 
    GENDER,
    (COUNT(CASE WHEN GENDER = 'FEMALE' THEN 1 END) /(SELECT COUNT(*) AS TOTALEMPLOYEES FROM HR)) *100 AS FEMALEpercentage ,
    (COUNT(CASE WHEN GENDER = 'MALE' THEN 1 END) /(SELECT COUNT(*) AS TOTALEMPLOYEES FROM HR)) *100 AS MALEpercentage, (count(case when attrition ='yes'then 1 end )/count(*)*100) as attritionrate,
    COUNT(*) AS EMPLOYEECOUNT
    FROM 
    HR 
    GROUP BY
    GENDER;
    
   -- DIFFERENCES IN ATTRITION RATES BASED ON EDUCATION FIELDS OR LEVELS

   SELECT 
   EDUCATIONFIELD,
   EDUCATION,
   COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END ) AS ATTRITIONCOUNT, 
   COUNT(*) AS TOTAL,
   (COUNT((CASE WHEN ATTRITION = 'YES' THEN 1 END))/COUNT(*) )*100 AS ATTRITIONRATE
   FROM 
   HR
   GROUP BY
   EDUCATIONFIELD,EDUCATION
   order by ATTRITIONRATE desc;
   
-- JOB ROLES WITH HIGHEST AND LOWEST ATTRITION RATES
SELECT
    JOBROLE,
    COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) / COUNT(*) * 100 AS ATTRITIONRATE
FROM
    HR
GROUP BY
    JOBROLE
ORDER BY
    ATTRITIONRATE DESC;
    
 
-- CALCULATE ATTRITION RATES AND AVERAGE TRAINING TIMES BY JOB ROLE
SELECT
    JOBROLE,
    AVG(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END) AS ATTRITIONRATE,
    AVG(TRAININGTIMESLASTYEAR) AS AVGTRAININGTIMES
FROM
   HR
GROUP BY
    JOBROLE;
    
    --   RELATIONSHIP BETWEEN PERFORMANCE RATINGS AND ATTRITION RATES
SELECT PERFORMANCERATING ,AVG(CASE WHEN ATTRITION ='YES' THEN 1 ELSE 0  END ) AS ATTRITIONRATE
 FROM HR 
 GROUP BY PERFORMANCERATING;

--  DOES EMPLOYEE SATISFACTION (ENVIRONMENT SATISFACTION, JOB SATISFACTION, RELATIONSHIP SATISFACTION) IMPACT ATTRITION
SELECT
    RELATIONSHIPSATISFACTION,
    ENVIRONMENTSATISFACTION,
    JOBSATISFACTION,
    ROUND(((RELATIONSHIPSATISFACTION + ENVIRONMENTSATISFACTION + JOBSATISFACTION) / (3 * 5)) * 100, 2) AS SATISFACTIONPERCENTAGE,
    COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) / COUNT(*) * 100 AS ATTRITIONRATE
FROM
    HR
GROUP BY
    RELATIONSHIPSATISFACTION,
    ENVIRONMENTSATISFACTION,
    JOBSATISFACTION
ORDER BY
    SATISFACTIONPERCENTAGE DESC;
 
 -- WORK-LIFE BALANCE IMPACT THE NUMBER OF YEARS AN EMPLOYEE STAYS WITH THE COMPANY
SELECT WORKLIFEBALANCE,AVG(YEARSATCOMPANY) AS AVGYEARSATCOMPANY
 FROM HR
 GROUP BY WORKLIFEBALANCE ;
 SELECT
    WORKLIFEBALANCE,
    AVG(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END) AS ATTRITIONRATE
FROM
   HR
GROUP BY
    WORKLIFEBALANCE
    order by ATTRITIONRATE DESC;

-- CORRELATION BETWEEN THE TOTAL WORKING YEARS AND ATTRITION RATES
SELECT
    TOTALWORKINGYEARS,
    AVG(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END) AS ATTRITIONRATE
FROM
   HR
GROUP BY
    TOTALWORKINGYEARS order by ATTRITIONRATE DESC;

-- DIFFERENCE IN ATTRITION RATES BASED ON THE DISTANCE FROM HOME OR THE DAILY RATE OF EMPLOYEES
SELECT DISTANCEFROMHOME, AVG(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END)  AS ATTRITIONRATE
  FROM HR
  GROUP BY DISTANCEFROMHOME order by ATTRITIONRATE DESC;
  
  -- MONTHLY INCOME OR SALARY HIKES INFLUENCE ATTRITION
SELECT
 MONTHLYINCOME,
 AVG(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END)  AS ATTRITIONRATE
  FROM HR
  GROUP BY MONTHLYINCOME;

--  EMPLOYEES WHO STAY LONGER WITH THE COMPANY MORE LIKELY TO GET PROMOTIONS
 SELECT
    YEARSATCOMPANY,
   ( count(CASE WHEN YEARSSINCELASTPROMOTION > 0 THEN 1  END)/count(*) ) * 100 AS PROMOTIONRATE
FROM
HR
GROUP BY
    YEARSATCOMPANY order by PROMOTIONRATE desc ;
  


--  NUMBER OF YEARS IN THE CURRENT ROLE AFFECT ATTRITION RATES  
SELECT 
    YEARSINCURRENTROLE,
    AVG(CASE
        WHEN ATTRITION = 'YES' THEN 1
        ELSE 0
    END) AS ATTRITIONRATE
FROM
    HR
GROUP BY YEARSINCURRENTROLE
ORDER BY ATTRITIONRATE DESC;
  
  -- IS THERE A PARTICULAR DEPARTMENT WITH CONSISTENTLY HIGH OR LOW ATTRITION RATES
  SELECT DEPARTMENT ,AVG(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END)  AS ATTRITIONRATE
  FROM HR
  GROUP BY DEPARTMENT;
  
  -- ARE THERE ANY TRENDS IN THE RELATIONSHIP BETWEEN EMPLOYEE EDUCATION LEVEL AND DEPARTMENT
  SELECT
    DEPARTMENT,
    EDUCATION,
    COUNT(*) AS EMPLOYEECOUNT,
    COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY DEPARTMENT) * 100 AS PERCENTAGEINDEPARTMENT
FROM
    HR
GROUP BY
    DEPARTMENT,
    EDUCATION
    order by PERCENTAGEINDEPARTMENT desc ;

--  DOES THE WORK ENVIRONMENT SATISFACTION IMPACT JOB SATISFACTION AND, IN TURN, ATTRITION

 SELECT
    ENVIRONMENTSATISFACTION,
    AVG(JOBSATISFACTION) AS AVGJOBSATISFACTION,
   ( COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END)/COUNT(*)*100) AS ATTRITIONRATE
FROM
HR
GROUP BY
    ENVIRONMENTSATISFACTION
    ORDER BY ATTRITIONRATE desc;
    
    -- IS THERE ANY RELATIONSHIP BETWEEN JOB INVOLVEMENT AND ATTRITION

SELECT JOBINVOLVEMENT ,
( COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END)/COUNT(*)*100) AS ATTRITIONRATE
 FROM HR
 GROUP BY JOBINVOLVEMENT
 ORDER BY JOBINVOLVEMENT;
 
 -- DO EMPLOYEES WITH HIGHER LEVELS OF EDUCATION PERFORM BETTER OR HAVE HIGHER JOB SATISFACTION
SELECT 
EDUCATION,AVG(JOBSATISFACTION)AS AVGJOBSATISFACTION,
AVG(PERFORMANCERATING) AS AVGPERFORMANCERATING
 FROM HR 
GROUP BY EDUCATION;

-- HOW DOES THE EDUCATION LEVEL AFFECT THE NUMBER OF COMPANIES AN EMPLOYEE HAS WORKED FOR
SELECT EDUCATION ,
AVG(NUMCOMPANIESWORKED)AS AVGNUMCOMPANIESWORKED 
FROM HR
GROUP BY EDUCATION;






